### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by ofuochi** [esimakin/twbs-pagination#117]
Am new to web programming. There seem not to be any documentation on how to install the plugin. Please how do I install it? which of the files should I include in my html header?

**Comment by esimakin** [comment]
Hi!
You can checkout the `gh-pages` branch and see in code (for e.g. [index.html](https://github.com/esimakin/twbs-pagination/blob/gh-pages/index.html))

**Comment by ofuochi** [comment]
Thank you, it worked. I included these in my header 

`<script  type="text/javascript" src="assets/js/custom_js/Gruntfile.js"></script>
	<script  type="text/javascript" src="assets/js/custom_js/jquery.twbsPagination.js"></script>
	<script  type="text/javascript" src="assets/js/custom_js/jquery.twbsPagination.min.js"></script>`

**Comment by vatnoise** [comment]
@ofuochi You only need to include either `jquery.twbsPagination.js` or `jquery.twbsPagination.min.js`

The "normal" version is usually good only while you're developing the website (easier to debug problems) while the "min" version is great performance wise and that one is usually used on live websites.

**Comment by ofuochi** [comment]
@vatnoise Thanks for the insight, now I understand better.
