### ISSUE TITLE
How to use with laravel

### ISSUE THREAD

**Issue by ofuochi** [esimakin/twbs-pagination#118]
I always get this error from this line `href:{{number}}` when I try to use the `href` option
`Use of undefined constant number - assumed 'number'`
I have laravel 5.1 installed on my project, could this be the problem or is there something am doing wrong? How can I use the `href` option without getting this error?

**Comment by esimakin** [comment]
Hi!
Please, post your options here and if it possible some fiddle.

It may be integration issue or incorrect use of plugin options.
If the last, see examples on `gh-pages` branch.

**Comment by ofuochi** [comment]
I was able to solve this issue by specifying `hrefvariable:--number--` Lavravel uses the double braces `{{ }}` to hold variable. There was a conflict between them. However, am faced with a new issue. The active pagination button does not change accordingly with the href. Its stays at 1
