### ISSUE TITLE
$('.pagination').twbsPagination() function only init once

### ISSUE THREAD

**Issue by zhangmengxue** [esimakin/twbs-pagination#119]
I was do some operate on my data. When the data changes,I want to init pagination again,based on the new datas.

This seems impossible. 
Could help me find out why?

**Comment by AngeIII** [comment]
#66 #86 #11

**Comment by zhangmengxue** [comment]
@AngeIII I was doing this 
```
$('.pagination').twbsPagination('destory');
```
but I got an error:
Uncaught TypeError: Cannot read property 'apply' of undefined

And I keep seeing the code:

```
 $.fn.twbsPagination = function (option) {
        var args = Array.prototype.slice.call(arguments, 1);
        var methodReturn;

        var $this = $(this);
        var data = $this.data('twbs-pagination');
        var options = typeof option === 'object' ? option : {};

        if (!data) $this.data('twbs-pagination', (data = new TwbsPagination(this, options) ));
        if (typeof option === 'string') methodReturn = data[ option ].apply(data, args);

        return ( methodReturn === undefined ) ? $this : methodReturn;
    };
```

The error seems from this...

**Comment by AngeIII** [comment]
Please make fiddle, of codepen. I will see what is going wrong. 
Possibly your pagination is not initialized. 

Also we have test qunit for destroy method call, so it should be workable.

**Comment by zhangmengxue** [comment]
well ... the event name is destroy. spelling mistake..

**Comment by zhangmengxue** [comment]
It's finally work out.Thanks!

**Comment by xchz** [comment]
beautiful girl ！ 哈哈

**Comment by xchz** [comment]
Many people have this problem. Why not write to documents.

**Comment by AngeIII** [comment]
We are ready to receive pull requests. You can update documentation and community will review it.
