### ISSUE TITLE
Refresh option

### ISSUE THREAD

**Issue by wilariz** [esimakin/twbs-pagination#120]
Hello. 
I'm using the plugin and I have a feature of my  web, the totalPages are dinamic, always incremental way, when change the totalPages I call to initialice the plugin but it never change, just kept the paginator initial with totalPages initial. Is there any way to refresh the paginator changing the totalPages? 
Thanks for your help.
Greetings

**Comment by frozonfreak** [comment]
+1

**Comment by navid-dada** [comment]
+1

**Comment by navid-dada** [comment]
i found solution in this [SOF ](http://stackoverflow.com/questions/24961833/reset-total-pages-in-jquery-pagination-plugin) Link. in my case second solution worked as a charm :)

**Comment by bajian** [comment]
```
//refreshPagination
var refreshPagination = function(totalPages, visiblePages, clickCB) {
    $('#pagination').empty().removeData("twbs-pagination").unbind("page").twbsPagination({
        totalPages: totalPages,
        visiblePages: visiblePages,
        onPageClick: clickCB
    });
}
//usage
// refreshPagination(15,5,function(event, page){
// 	alert(page);
// });
```

**Comment by moxiaozhou** [comment]
+1

**Comment by zhangbobell** [comment]
get it! thx!

**Comment by esimakin** [comment]
Example added.
See docs on github.io
