### ISSUE TITLE
Issue when the URL got a space or a querystring variable with space or %20

### ISSUE THREAD

**Issue by JosephSKh** [esimakin/twbs-pagination#127]
There's an issue if the URL got a space or %20, the active page is not correct and always set to (1)

test a URL like this
"www.example.com?page=7&var=a a"

**SOLVED BY:**
replacing:

`var match, regexp = this.options.href.replace(/[-\/\\^$*+?.|[\]]/g, '\\$&');`

with

`var match, regexp = this.options.href.replace(/[-\/\\^$*+?.|[\]]/g, '\\$&').replace(' ','%20');`

**Comment by tonarii** [comment]
Hi JosephSKh, 
thanks for your solution !
But i'm still having an issue, this is working for a two words search but this is not working for a 3 words search or more.
Do you have any idea how to correct that ?
Thanks.
Regards.

**Comment by JosephSKh** [comment]
@tonarii Glad you solved it man and sorry for the late reply,, Hope it helped :)
Also, you can post your solution for others

Thank you :)

**Comment by tonarii** [comment]
@JosephSKh Hi, actually i used the solution posted by AnchorRen :
https://github.com/esimakin/twbs-pagination/issues/125

:)

**Comment by esimakin** [comment]
Fixed.
Closed
