### ISSUE TITLE
Update npm plugin to actual version

### ISSUE THREAD

**Issue by JayDi85** [esimakin/twbs-pagination#134]
http://npmjs.com/ contain old plugin version without "bootstrap 4 support" (code hasn't anchorClass option). Please, upload current version to npm and update docs with info "how-to support bootstrap 4". You can read about that in #133.

**Comment by kevindb** [comment]
@esimakin I sent an email to you and Cristian, the "owner" of the package on NPM to
1. Ask Cristian to update the package
2. Add you as a collaborator on NPM so that you can publish updates yourself.

I hope this is helpful. Thank you for the plugin.

**Comment by kevindb** [comment]
[NPM package](https://www.npmjs.com/package/twbs-pagination) has been updated to 1.4.1
