### ISSUE TITLE
Hiding when single page breaks functionality

### ISSUE THREAD

**Issue by richgoldmd** [esimakin/twbs-pagination#136]
There was a recent change that involves this code:

```
        // hide if only one page exists
        if (this.options.totalPages == 1) {
            return this;
        }
```
This breaks functionality, as the controls aren't built and the onPageClick is not called for the first page. In my project we use this to power an ajax driven data loader, by tearing down and rebuilding the control, but we never get the initial event to load the data. This functionality should be optional if it remains.

**Comment by esimakin** [comment]
Hi!
Please, check the fix

**Comment by richgoldmd** [comment]
Nice! Works perfectly. Thank you, and thanks for an excellent plugin
