### ISSUE TITLE
Reset paging

### ISSUE THREAD

**Issue by ltduc** [esimakin/twbs-pagination#137]
Hi, Team!

First, i have totalPages:  50, after data changed and totalPages:  20, i called again method twbsPagination but paging now working. How to solve my issue? 

Please, help suport me!

Thanks

**Comment by AngeIII** [comment]
The main idea to call destroy and initialize again.
see more in:
#11  #43 #119 #120 #42

**Comment by ltduc** [comment]
Method .twbsPagination("destroy")  done.
Thanks AngeIII!
