### ISSUE TITLE
Complex pagination (top fixed + bottom ...)

### ISSUE THREAD

**Issue by degenaro** [esimakin/twbs-pagination#138]
It would be desirable to have the both the pagination selector (page 1, 2, 3...next/prev) and the horizontal scroll bar fixed in a header so that they remain at the top of the page while vertical scrolling.  Already possible/configurable?

**Comment by esimakin** [comment]
Hi!
Look at syncronized pagination in docs (http://esimakin.github.io/twbs-pagination/)
You could hold on the top one of pagination elements with `position: fixed;` for e.g.

**Comment by degenaro** [comment]
Thx for your reply.  Not sure how this works, but Ill take a look. Seems to
apply only to the page selector, though.

What about the page content horizontal scroll bar?  When the data is wider
than the screen, a horizontal scroll appears at the bottom of the page.
How does one make the horizontal scroll bar stay fixed at the top of the
page?

**Comment by esimakin** [comment]
I'm pretty sure you can't move native browser scrollbar to the opposite side from js...
But you can hide it and use something like [this](http://manos.malihu.gr/jquery-custom-content-scroller/) or [this](https://jamesflorentino.github.io/nanoScrollerJS/) for customization
