### ISSUE TITLE
[solved] onPageClick self-run on page load

### ISSUE THREAD

**Issue by gubi** [esimakin/twbs-pagination#139]
The code in line 35~37 is bugged because run itself if `onPageClick` is defined.
Here the piece of code:

``` php
if (this.options.onPageClick instanceof Function) {
    this.$element.first().on('page', this.options.onPageClick);
}
```

I fixed by removing it and then adding the following code in line 225:

``` php
if (_this.options.onPageClick instanceof Function) {
    _this.options.onPageClick(evt, _this.currentPage);
}
```

Best regards and thank you for this plugin :+1:

**Comment by Richeir** [comment]
Thank you!! This trouble me a lot.

**Comment by AngeIII** [comment]
You can use : initiateStartPageClick: false isn'it?

**Comment by Richeir** [comment]
Just noticed in the  '$.fn.twbsPagination.defaults = {'
Thank you! @AngeIII 
I think this property should be 'false' in default...maybe.

**Comment by AngeIII** [comment]
Actually many people uses 
onPageClick event when pagination initializes. For example to fetch data from ajax, or to show some animations. Due to backward compatibility this option cannot be changed to false by default

**Comment by Richeir** [comment]
Got That.
Thanks for your contributions.
