### ISSUE TITLE
Out of order add

### ISSUE THREAD

**Issue by tpodom** [esimakin/twbs-pagination#14]
I ran into this jquery + Chrome issue when trying to use the plugin rendering 10 pages.  I was able to fix it by changing the buildListItems to return an array since jquery 1.8+ supports appending an array.  I can submit a pull request but wasn't sure if you wanted something that may break older than 1.8.

http://bugs.jquery.com/ticket/13505

**Comment by AngeIII** [comment]
@tpodom As you will submit pull request we will check. Thanks.
