### ISSUE TITLE
reference to global jQuery at 178 line

### ISSUE THREAD

**Issue by zmkn** [esimakin/twbs-pagination#140]
![image](https://cloud.githubusercontent.com/assets/1784566/19231316/fdc17f20-8f0b-11e6-8481-7be53ca62211.png)

Should it use a "$" at here?

**Comment by esimakin** [comment]
In some cases it can produce headache.
It should use method parameter `$` instead of global var.
Need to fix it!

**Comment by esimakin** [comment]
Will be in 1.4.2 release
