### ISSUE TITLE
A tiny inconvenience when using twbsPagination.

### ISSUE THREAD

**Issue by JimmyBenKlieve** [esimakin/twbs-pagination#141]
``` HTML
<ul id="my-pagination" class="pagination pagination-sm">
</ul>
```

Every time I

``` javascript
$('#my-pagination').twbsPagination('destroy');
$('#my-pagination').twbsPagination({
  totoalPages: iExpectPages,
  startPage: Math.min(iExpectPages, iCurrentPage),
});
```

then I have to re-setup my event listener using jQuery `on` method, though I've done this at the very first time.

``` javascript
$('#my-pagination').on('page', (e, p) => { /*my code goes here*/ });
```

So I read the code, found at [line 89](https://github.com/esimakin/twbs-pagination/blob/master/jquery.twbsPagination.js#L89) caused this tiny inconvenience.

In my opnion, I don't think you need to do `this.$element.off('page')` in `destroy` method, because might I have more than one event listener listening `page` event.
Plugin version: 1.4.1

**Comment by AngeIII** [comment]
If we will not use off this will be a possible memory leak.
