### ISSUE TITLE
After Using 'initiateStartPageClick: false' selected page background is not changing

### ISSUE THREAD

**Issue by coddyrabbit** [esimakin/twbs-pagination#146]
After Using '**initiateStartPageClick**: false' selected page background is not changing, but every thing works good apart from this. 

 $('#pagination').twbsPagination({
            startPage: 1,
            totalPages: total,
            initiateStartPageClick: false,
            visiblePages: 12,
            onPageClick: function (event, page) {
                var catId = $('input:radio[name="category"]:checked').val();
                $("html, body").animate({ scrollTop: 0 }, "slow");
                scope.getBusiness(,page,12,catId);
            }
        });

**Comment by Ectropy** [comment]
Are you trying to change the background via JavaScript or something like that? I didn't see where that would be done in your code. Perhaps in getBusiness?

**Comment by AngeIII** [comment]
@coddyrabbit make onPageClick function by variable and just run it on document.ready.
```
 function (event, page) {
var catId = $('input:radio[name="category"]:checked').val();
$("html, body").animate({ scrollTop: 0 }, "slow");
scope.getBusiness(,page,12,catId);
}
```

**Comment by coddyrabbit** [comment]
Tanks for your reply issue resolved

**Comment by zhujinhu21** [comment]
@coddyrabbit I have the same problem..how did you to solve it
