### ISSUE TITLE
Display total number of pages

### ISSUE THREAD

**Issue by smartcorestudio** [esimakin/twbs-pagination#23]
Is it possible to display total number of pages?
Something like this:
```
[1][2][3][4][5]...[28]
```
(User can see that there are 28 pages in this example)

**Comment by ImranAhmed** [comment]
Did this ever get done? Seems liek a sensible addition.

**Comment by esimakin** [comment]
This feature is not compatible with current concepts.

**Comment by esimakin** [comment]
Consider use alternatives.
For e.g. https://github.com/flaviusmatis/simplePagination.js

**Comment by AngeIII** [comment]
@esimakin , I will implement currently this in one hour.

**Comment by esimakin** [comment]
@AngeIII, submit the pull request.
Do not commit to master, yet
