### ISSUE TITLE
Refresh pagination after ajax request changing items count

### ISSUE THREAD

**Issue by pawprosk** [esimakin/twbs-pagination#24]
Hello, 

Is it possible to add feature for refreshing / destroying instance of pagination in real-time?

Example - pagination is connected with ajax request which shows as many items on list as user select - pagination can be initialised only once (no refresh / destroy method).

**Comment by MarkBuyEfficient** [comment]
Did you resolve this issue? I have the same question

**Comment by pawprosk** [comment]
As I closed issue here is my solution:

HTML:
    ...
      <td style="display:none" id="paginateBox"><div id="paginate"></div></td>
    ...

**Comment by pawprosk** [comment]
HTML 

    <td  style="display:none" id="paginateBox"><div id="paginate"></div></td>

jQuery
    function showPagination(pagesCounter){
	
	$('#paginate').remove();
	$('#paginateBox').html("<div id='paginate'></div>");
	$('#paginate').twbsPagination({
	  totalPages: pagesCounter,
	  visiblePages: 5,
	  first: "<img src='img/sprevious.png' alt='pierwsza'/>",
	  prev: "<img src='img/previous.png' alt='poprzednia'/>",
	  next: "<img src='img/next.png' alt='następna'/>",
	  last: "<img src='img/snext.png' alt='ostatnia'/>",
	  onPageClick: function (event, page) {
			var activeTable = $(".tableTable").attr("id");	
	  }
	});
    }

And simple ajax request:

    function refreshData(){
		$.post("url", {data},function(data) {
				if(paginationPagesTotal >1){
					showPagination(paginationPagesTotal);
					$("#paginateBox").show();
				}else
					$("#paginateBox").hide();
			});
	}

**Comment by pawprosk** [comment]
Hello,

Yes i have, i wrote answer :
https://github.com/esimakin/twbs-pagination/issues/24

2015-03-17 17:35 GMT+01:00 MarkBuyEfficient <notifications@github.com>:

**Comment by zuukaer** [comment]
That's bad,why do I have to remove the item and regenerate it,it's bad.....

**Comment by mattNit** [comment]
Was a better solution ever found for this?

**Comment by BuyEfficient** [comment]
Hi!

I took over this account for a former co-worker. The work was frozen, and I do not have any insights to share with you on it.

Take care,

Jared

**Comment by ngrcode** [comment]
Hi I have the same problem and use this solution and it worked but after that I have another problem that it 
send request not one time for many times and it doesnt stop loading that page what can I do please help me It has taken my time for two days

**Comment by josecebe** [comment]
@ngrcode Could you try this?: https://github.com/esimakin/twbs-pagination/pull/175 and https://github.com/esimakin/twbs-pagination/pull/173

The new method to refresh the pagination element is:

$pagination.twbsPagination("changeTotalPages", 100, 1);

100 = New total pages
1 = New actual page
