### ISSUE TITLE
change page numbers using script?

### ISSUE THREAD

**Issue by aftabsharif** [esimakin/twbs-pagination#33]
Can we change total page numbers using jquery? as if default page numbers are 30 now if i change per page entries from 10 to 20 then how can i change total number of pages according to 20 without refresh...

**Comment by esimakin** [comment]
Try this http://jsfiddle.net/eugenespb/zLq2xvfy/

**Comment by aftabsharif** [comment]
Thank you sooooooooooooo much 






Sent from Windows Mail





From: Eugene
Sent: ‎Thursday‎, ‎January‎ ‎8‎, ‎2015 ‎10‎:‎06‎ ‎PM
To: esimakin/twbs-pagination
Cc: AFTAB SHARIF





Try this http://jsfiddle.net/eugenespb/zLq2xvfy/
