### ISSUE TITLE
request: add options, displays item-per-page instead of page number

### ISSUE THREAD

**Issue by gitlovenotwar** [esimakin/twbs-pagination#34]
Hi, great work on creating in this pagination using jquery. I would like somehow to add some extension(options), something like:

$('#pagination').twbsPagination({
     totalPages: 100,
    itemPerPage: 10, // the number of items in the page
});

so the output will be:
[1-10] [11-20] [21-30]....

Thanks.

**Comment by esimakin** [comment]
You mean something like this http://jsfiddle.net/eugenespb/m546Lzxw/ ?

**Comment by gitlovenotwar** [comment]
yes, exactly like that :)

**Comment by AngeIII** [comment]
My comment: https://github.com/esimakin/twbs-pagination/issues/26#issuecomment-153687552
Show an example how to make group. 

Related to: #39 , #26, #46
