### ISSUE TITLE
request: add .disable() and .enable() method

### ISSUE THREAD

**Issue by tinpont** [esimakin/twbs-pagination#35]
Is there anyway to stop user click the page button when requesting data?

**Comment by esimakin** [comment]
I added methods `enable` and `disable`. Look ar branch #35

**Comment by tinpont** [comment]
Thanks, esimakin. GJ.

**Comment by jgonzo127** [comment]
Could we see a working example of this?

**Comment by esimakin** [comment]
TODO: Add it to the master

**Comment by esimakin** [comment]
Done
