### ISSUE TITLE
Grouped pages in pagination issue

### ISSUE THREAD

**Issue by www741147** [esimakin/twbs-pagination#39]
Is there a option to display input that jump to specific page,when I click the button, it will jump to the page.
http://jsfiddle.net/eugenespb/m546Lzxw/

**Comment by btafoya** [comment]
I too am trying to implement this option. I have attempted simply calling...

jQuery(".pastweeks-pagination").twbsPagination({startPage: 4});

but that does not work.

Thanks in advance!

**Comment by www741147** [comment]
I also want to have a good idea that can work well.

**Comment by AngeIII** [comment]
See my comment how to implement grouped items per page.
Items also can be a page :)
https://github.com/esimakin/twbs-pagination/issues/26#issuecomment-153687552
