### ISSUE TITLE
Not working with jquery 1.9.1

### ISSUE THREAD

**Issue by fredbutters** [esimakin/twbs-pagination#41]
From what I can tell by toggling jQuery versions in JSFiddle it works with all other versions > 1.7.2 but with jQuery 1.9.1 he buttons are rendered out of order. Otherwise it's great, thanks!

![image](https://cloud.githubusercontent.com/assets/3720902/6562662/4ab3398c-c658-11e4-992f-08d5957307c0.png)

http://jsfiddle.net/barryman9000/DTcHh/5318/

**Comment by PanuO** [comment]
Yeah i'm experiencing same problem. Rendered code is:
<ul id="userPagination" class="pagination-sm pagination">
  <li class="page">
    <a href="#">11</a>
  </li>
  <li class="page">
    <a href="#">9</a>
  </li>
  <li class="page">
    <a href="#">1</a>
  </li>
  <li class="page active">
    <a href="#">2</a>
  </li>
  <li class="page">
    <a href="#">3</a>
  </li>
  <li class="prev">
    <a href="#">Prev</a>
  </li>

**Comment by esimakin** [comment]
Need more info about environment

**Comment by AngeIII** [comment]
@PanuO , @fredbutters which browser is used?
For me works fine. With fiddle you provided.

**Comment by AngeIII** [comment]
Fixed in 1.3.1v
