### ISSUE TITLE
Refresh or redraw pagination?

### ISSUE THREAD

**Issue by foxyPL** [esimakin/twbs-pagination#43]
Hey,
What should I do when i want to refresh/ redraw pagination?
I'm doing ajax POST and when my data are returned, I want to:
- go to the first page
- refresh count of pages
- redraw pagination

How can I achive this?

**Comment by tincho89** [comment]
Hi, I just had the same problem.
Check the answer here: https://github.com/esimakin/twbs-pagination/issues/24

**Comment by guyisra** [comment]
The fastest, cleanest way I found is to do

```
if($('.pagination').data("twbs-pagination")){
					$('.pagination').twbsPagination('destroy');
				}

				$('.pagination').twbsPagination({
				  totalPages: data["pages"],
				  visiblePages: 3,
				  start_page: page,
				  onPageClick: function (event, next_page) {
				  	params.page = next_page;
				  }
				});
```

which checks if there a data attribute in the pagination nodes and if so uses the twbsPagination destroy function to clear itself out. Then redo the pagination

**Comment by jnv22** [comment]
This solution is the best.  I implemented it without any problems

**Comment by fan576679268** [comment]
thank you guyisra very much, it help me~

**Comment by colonia** [comment]
many thanks to guyisra

**Comment by pineladsn** [comment]
great solution guyisra :+1:

**Comment by cristozz** [comment]
@guyisra!! tienes razon!!

**Comment by sayajin101** [comment]
@guyisra your solution worked 100% first try, ty

**Comment by josecebe** [comment]
Hi @sayajin101 , if you are using the latest version (v1.4.2) you can use the new method 'changeTotalPages' instead.

You can read more info about how to use it in here: https://github.com/josecebe/twbs-pagination/issues/172

**Comment by xavierluz** [comment]
https://www.js-tutorials.com/jquery-tutorials/simple-example-pagination-using-jquery-bootstrap/
