### ISSUE TITLE
how to change chinese

### ISSUE THREAD

**Issue by zc0315** [esimakin/twbs-pagination#44]
how to change chinese

**Comment by zc0315** [comment]
I change its conf to do it.

**Comment by zangbianxuegu** [comment]
What do you mean to change chinese ?

**Comment by jieyou** [comment]
paginationArea.twbsPagination({
					totalPages: 35,
					startPage:2,
					first:'第一页',
					prev:'上一页',
					next:'下一页',
					last:'最后页',
					onPageClick: function (event, page) {
						alert('Page ' + page);
					}
				})
