### ISSUE TITLE
reach the function outside of plugin

### ISSUE THREAD

**Issue by sakirayan78** [esimakin/twbs-pagination#45]
hi
my question is how can we reach the function outside of the plugin.for example,  var pager =  $('#pagination-demo').twbsPagination({
            totalPages: 35,
            visiblePages: 7
          
        });
//how can I reach the render function here .thankx
        console.log(pager.prototype.render());

**Comment by esimakin** [comment]
Hello,
you can use `page.twbsPagination('render', 'some_arguments')`
