### ISSUE TITLE
can this will work in list item ?

### ISSUE THREAD

**Issue by ezekel** [esimakin/twbs-pagination#46]
Hi, I want to paginate my list item is this will work ?, also I am having problem on how to implement this to paginate my items, for example my default items will display 10 items each page, If I click the page2 or btn2 this will query to my table to get the records 11-20,then If I click to page3 this will query to 21-30,
and display this to my ul.can you help me please, this is my first time to use this plugin.I hope you can help me.

Thank you in advance.

**Comment by AngeIII** [comment]
@esimakin , see my comment in: https://github.com/esimakin/twbs-pagination/issues/26#issuecomment-153687552

I tried to crate example for items_per_page functionality.
