### ISSUE TITLE
twbs pagination error if result is zero

### ISSUE THREAD

**Issue by ezekel** [esimakin/twbs-pagination#48]
why I get error if my count result is zero ?

``
  "Error: Start page option is incorrect"
``

``` javascript
 $.ajax({
       type:'post,
       url:'fetchEmployeeProject',
       data:{id:4},
       success:function(data){
           $('#mypagination').twbsPagination({
              totalPages: data, //error if data is zero.
              visiblePages: 7,
              onPageClick: function (event, page) {

                  $('#divcontainer').load('load_data.php',{id:4});


              }
          });

       }

   });
```

**Comment by esimakin** [comment]
Hi ezekel,

look at lines from [22](https://github.com/esimakin/twbs-pagination/blob/master/jquery.twbsPagination.js#L22) to [35](https://github.com/esimakin/twbs-pagination/blob/master/jquery.twbsPagination.js#L35). Here is checked init options.
Plugin not supported zero `totalPages` and negative `startPage`.
