### ISSUE TITLE
Visible Pages > Total Pages

### ISSUE THREAD

**Issue by randdusing** [esimakin/twbs-pagination#49]
I noticed that you could set visible pages to a value greater than total pages. Minor "bug", but something I thought you may want to fix.

**Comment by esimakin** [comment]
I've tested it and nothing bad happens.
Do you think it throwing error if that options is incorrect?

**Comment by randdusing** [comment]
I tried recreating, and now I don't see any issue. Maybe there was something else I was doing that caused the issue.
