### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by yairEO** [esimakin/twbs-pagination#52]
Iterating the same set multiple times is deeply unwise when it can be done easily and once.

Current code:

    children.filter(function () {
        return $(this).data('page') === pages.currentPage && $(this).data('page-type') === 'page';
    }).addClass(this.options.activeClass);

    children.filter(function () {
        return $(this).data('page-type') === 'first';
    }).toggleClass(this.options.disabledClass, pages.currentPage === 1);

    children.filter(function () {
        return $(this).data('page-type') === 'last';
    }).toggleClass(this.options.disabledClass, pages.currentPage === this.options.totalPages);

    children.filter(function () {
        return $(this).data('page-type') === 'prev';
    }).toggleClass(this.options.disabledClass, !this.options.loop && pages.currentPage === 1);

    children.filter(function () {
        return $(this).data('page-type') === 'next';
    }).toggleClass(this.options.disabledClass, !this.options.loop && pages.currentPage === this.options.totalPages);

## Should be:

    var that = this,
          children = this.$listContainer.children();

    children.each(function () {
        var $this = $(this),
            data = $this.data();

        if( data.page === pages.currentPage && data.pageType === 'page' )
            $this.addClass(that.options.activeClass);

        if( data.pageType === 'first' )
            $this.toggleClass(that.options.disabledClass, pages.currentPage === 1);

        if( data.pageType === 'last' )
            $this.toggleClass(that.options.disabledClass, pages.currentPage === that.options.totalPages);

        if( data.pageType === 'prev' )
            $this.toggleClass(that.options.disabledClass, !that.options.loop && pages.currentPage === 1)

        if( data.pageType === 'next' )
           $this.toggleClass(that.options.disabledClass, !that.options.loop && pages.currentPage === that.options.totalPages);
    });

**Comment by esimakin** [comment]
Can you submit pull request?

**Comment by yairEO** [comment]
sorry, i'm too busy. just copy paste this into your code, replacing the current code. no big deal
