### ISSUE TITLE
Why my first page/startPage does not show at load time? 

### ISSUE THREAD

**Issue by sgon00** [esimakin/twbs-pagination#53]
Hi, I am getting crazy with this issue. I did google and tried to solve it for 2 days. But no luck.

I followed the example shown in the doc. But why doesn't my first page load at page load time?

The content is just empty. After load, if I click page 2 and then click page 1 back, the first page will be shown. I have no idea why. I even tried to define startPage: 1 which is useless since that is default value. but no luck. Thank you very much for your help.

**Comment by sgon00** [comment]
I figured it out. Simply add:

```
.trigger('page', 1);
```

```
$('#pagination-demo').twbsPagination({...}).trigger('page', 1);
```

The first page content loaded should be default. If it's not, at least the doc should mention it. 
It took me 49 hours to figure this out....

**Comment by esimakin** [comment]
Yes, you're right about trigger page.
In the past, code had [trigger action](https://github.com/esimakin/twbs-pagination/blob/698c6a293e2d5461858c77156ccd3d1dc301d9ed/jquery.twbsPagination.js#L69).

But then line has been removed. I can't remember why...
