### ISSUE TITLE
small optimization for jquery

### ISSUE THREAD

**Issue by AngeIII** [esimakin/twbs-pagination#56]
currently in js I see:
```
            this.$element.first().on('page', this.options.onPageClick);
```

which possibly can simply changed to:
```
            this.$element.on('page', this.options.onPageClick);
```

@esimakin , maybe you know what is a purpose for first() and maybe it is not needed?

as we know $element always should be a single, so first() doesnt make sense?

**Comment by esimakin** [comment]
Need to check multiple paginators.
@AngeIII , see *Synchronized pagination elements* example at gh-pages branch

**Comment by AngeIII** [comment]
Work fine on gh-pages without first()
