### ISSUE TITLE
Introduce Next/Prev pagination

### ISSUE THREAD

**Issue by AngeIII** [esimakin/twbs-pagination#57]
Will be nice if it will be available just Prev|Next pagination
![image](https://cloud.githubusercontent.com/assets/3625675/11000203/01d9f7d6-84a9-11e5-9f15-0589605cd8e9.png)

**Comment by AngeIII** [comment]
This is possible to done without big troubles.

need check for visiblePages: 0

**Comment by AngeIII** [comment]
Can be done:
```
visiblePages: 0,
first: false,
last: false,
```

**Comment by esimakin** [comment]
Need to check `Pager`
![screenshot from 2015-11-07 21-21-06](https://cloud.githubusercontent.com/assets/6294728/11016534/977fa76c-8595-11e5-850d-3c44f4628d66.png)
![screenshot from 2015-11-07 21-21-21](https://cloud.githubusercontent.com/assets/6294728/11016535/9780d51a-8595-11e5-9a99-71da20c6690d.png)

**Comment by AngeIII** [comment]
It works isn't it?

**Comment by esimakin** [comment]
Not exactly.
Margin losses

**Comment by AngeIII** [comment]
@esimakin it is whitespace issue in getbootstrap pages. We have correct behaviour. Just only maybe needed :before { margin-left: 2px; }

issue:
in bootstrap:
```
<ul>
   <li>...</li><!-- whitespace there-->
   <li>...</li>
</ul>
```

but in our plugin without whitespaces
```
<ul><li>....</li><li>...</li></ul>
```

**Comment by AngeIII** [comment]
I think needed new issue ticket in bootstrap:). It is bootstrap issue.

**Comment by AngeIII** [comment]
Bootstrap v3 have major impact of this, so it is not fixed. But in v4 bootstrap it seems they will try to redesign more correctly. As for now we only can add `margin-left: 2px;` if needed
