### ISSUE TITLE
Next release [1.4.2]

### ISSUE THREAD

**Issue by esimakin** [esimakin/twbs-pagination#58]
TODO:
- [ ] Docs
- [x] Method `getCurrentPage`
- [ ] `enable()` and `disable()` methods from #35 
- [ ] ...

**Comment by AngeIII** [comment]
2) you want it as option like :
```
twbsPagination({
    pageText: function(page) {
         return: '['+page+']';
    }
});

or just like method in prototype?

**Comment by esimakin** [comment]
Not exactly.
Option `page` (or `pageText` - needful to be choose) will accept `string` or `function`

**Comment by avinoth** [comment]
@esimakin I've updated the documentation with the current set of features developed and available here. Where should I target the PR to?

https://github.com/avinoth/twbs-pagination/tree/gh-pages-develop

**Comment by esimakin** [comment]
TODO examples:
- show method
- bootstrap 4 in iframe
- link with settings to another plugin which does show first and last pages as numbers
