### ISSUE TITLE
Get current page - How To

### ISSUE THREAD

**Issue by gittix09** [esimakin/twbs-pagination#59]
How can we retrieve the number of the page that is currently selected? 
Please note that it can ofcourse be different from the "startPage" param

**Comment by AngeIII** [comment]
Currently it is only possible to get by events
event driven (current_page possibly can be undefined/false/null)
```
 var current_page;
 jQuery(document).on('page',function(event, page) {
    current_page = page;
    console.log('current_page', current_page);
  });
```
same for onPageClick method
