### ISSUE TITLE
Paging function runs when pager initialized.  Don't want it to

### ISSUE THREAD

**Issue by versute** [esimakin/twbs-pagination#64]
I am getting the results of the first page through AJAX, then creating the paging control.  The function that is to run on page changed gets run, causing my app to do the exact search over again.  How do I prevent the function from executing when it initializes?  I only want it to run when a paging control is clicked, not when it's first created.

**Comment by AngeIII** [comment]
initiateStartPageClick: false

**Comment by versute** [comment]
Perfect, thanks!
