### ISSUE TITLE
Is there any config via which I can disable backward moment in pagination option?

### ISSUE THREAD

**Issue by evivz** [esimakin/twbs-pagination#67]
Is there any config via which I can disable backward moment in pagination option

**Comment by esimakin** [comment]
Hi,
you can use `prev` and `first` options, if I understand you correctly.

Example:
```javascript
   $('#pagination-demo').twbsPagination({
        totalPages: "35",
        visiblePages: "10",
        prev: false,
        first: false
    });
```

But it is in any case user can move backward.
If you want truly disable this, you'll have to change render algorithm.

**Comment by esimakin** [comment]
Out of date.
Closed
