### ISSUE TITLE
Not update item class to active when call show method

### ISSUE THREAD

**Issue by yigityuce** [esimakin/twbs-pagination#84]
Hi,

I tried to update current page when document is ready, with this:

$('#pagination').twbsPagination('show', page-number);

But when i did this it didn't set the list item(page-number) class to "active". How can i do this?

Thanks.

**Comment by AngeIII** [comment]
Should work. Can tpu provide tulk code for example in codepen or fiddle?

**Comment by yigityuce** [comment]
Hi again,

Here is a not working code [https://jsfiddle.net/y4zwaha3/](https://jsfiddle.net/y4zwaha3/)
But i found why it is not working. The show method is called with string type page number in my code, but it should be an integer. So i fixed the problem with this: [https://jsfiddle.net/9okwL2tf/](https://jsfiddle.net/9okwL2tf/)

Maybe you can add control or conversion at the beginning of the function. Thanks for your quick reply btw.
