### ISSUE TITLE
Jump/Go To Page Option

### ISSUE THREAD

**Issue by sandesh583** [esimakin/twbs-pagination#85]
I would like to thank you for developing this plugin. I am using this plugin in one of my major project and came across the issue of Jumping to a page. Would you please either guide me how can I re-use your function in order to achieve that without page reload. 

Or can you introduce it as a new feature.

**Comment by AngeIII** [comment]
Just use show method in widget? 

If you pages are located in different request (page reload) you should make them prefetch in ajax and then call pagination.

**Comment by TheHooper** [comment]
e..  how can i use the show method? i don't know how to call it

**Comment by esimakin** [comment]
Out of date. Closed.

PS. Any jQuery plugin method can be called with `$(selector).pluginName('methodName');`
See for details https://github.com/jquery-boilerplate/jquery-patterns/blob/master/patterns/jquery.basic.plugin-boilerplate.js
